version: '3.0'

services:

  # node
  node:
    image: 'futaro/mecab-node:latest'
    volumes:
      - ./app:/opt/app
    env_file: .env
    working_dir: /opt/app
    command: npm run start

networks:
  default:
    external:
      name: hubot_link
